import { Button } from '@components/button';
import { ThemeToggle } from '@components/theme-toggle/theme-toggle';
import { TwoColumn } from '@layouts/TwoColumn';
import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className=''>
        <section>
          <ThemeToggle />
        </section>
        <TwoColumn
          leftChildren={
            <div className='grid h-full w-full grid-cols-4 place-items-center gap-4 '>
              <Button variant='filled' size='medium' className='ring-o'>
                compound
              </Button>
              <Button variant='light' size='medium' className=''>
                compound
              </Button>
              <Button disabled variant='outline' size='medium'>
                compound
              </Button>
              <Button variant='subtle' size='medium'>
                compound
              </Button>
            </div>
          }
          rightChildren={<h1 className='p- text-4xl text-green-600'>Right</h1>}
        />
      </main>
    </div>
  );
}
